# Nome del workflow che vedi su GitHub
name: Deploy to Firebase Hosting

# Questo dice a GitHub di eseguire il workflow
# sia quando fai un push sul ramo "main"
# sia quando una pull request viene unita a "main"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    # Usa l'ultima versione di ubuntu come sistema operativo
    runs-on: ubuntu-latest
    steps:
      # 1. Scarica il codice del tuo repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installa le dipendenze e crea la versione di produzione del sito
      - name: Install dependencies and build
        run: npm ci && npm run build

      # 3. Fa il deploy su Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARCATEMPOTCS }}'
          channelId: live
          projectId: marcatempo-tcs
